<?php

/**
 * @file
 * Contains vppn.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function vppn_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the vppn module.
    case 'help.page.vppn':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('View Permissions Per Node') . '</p>';
      return $output;

    default:
  }
}
`